Dicedragons/src/Entity/Partida.php
<?php

namespace App\Entity;

use App\Repository\PartidaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PartidaRepository::class)
 */
class Partida
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class, inversedBy="partidas")
     */
    private $Usuario;

    /**
     * @ORM\ManyToMany(targetEntity=Personaje::class, inversedBy="partidas")
     */
    private $Personajes;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Proxima_sesion;

    public function __construct()
    {
        $this->Personajes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->Usuario;
    }

    public function setUsuario(?Usuario $Usuario): self
    {
        $this->Usuario = $Usuario;

        return $this;
    }

    /**
     * @return Collection|Personaje[]
     */
    public function getPersonajes(): Collection
    {
        return $this->Personajes;
    }

    public function addPersonaje(Personaje $personaje): self
    {
        if (!$this->Personajes->contains($personaje)) {
            $this->Personajes[] = $personaje;
        }

        return $this;
    }

    public function removePersonaje(Personaje $personaje): self
    {
        $this->Personajes->removeElement($personaje);

        return $this;
    }

    public function getProximaSesion(): ?\DateTimeInterface
    {
        return $this->Proxima_sesion;
    }

    public function setProximaSesion(\DateTimeInterface $Proxima_sesion): self
    {
        $this->Proxima_sesion = $Proxima_sesion;

        return $this;
    }
}

Dicedragons/src/Entity/Razas.php
<?php

namespace App\Entity;

use App\Repository\RazasRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RazasRepository::class)
 */
class Razas
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nombre;

    /**
     * @ORM\Column(type="text")
     */
    private $Descripcion;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(string $Descripcion): self
    {
        $this->Descripcion = $Descripcion;

        return $this;
    }

    public function __toString()
    {
        return $this->Nombre;
    }
}

Dicedragons/src/Form/PartidaType.php
<?php

namespace App\Form;

use App\Entity\Partida;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartidaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Proxima_sesion')
            ->add('Usuario')
            ->add('Personajes')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Partida::class,
        ]);
    }
}

Dicedragons/src/Controller/PartidaController.php
<?php

namespace App\Controller;

use App\Entity\Partida;
use App\Entity\Personaje;
use App\Form\PartidaType;
use Doctrine\ORM\EntityManagerInterface;

use App\Repository\PartidaRepository;
use App\Repository\PersonajeRepository;
use App\Repository\UsuarioRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/partida')]
class PartidaController extends AbstractController
{
    #[Route('/', name: 'partida_index', methods: ['GET'])]
    public function index(PartidaRepository $partidaRepository, PersonajeRepository $personajeRepository): Response
    {   $p = $personajeRepository->findAll();
        return $this->render('partida/index.html.twig', [
            'partidas' => $partidaRepository->findAll(),
            'pe' => $p
        ]);
    }

    #[Route('/partidas_propias', name: 'partida_propia', methods: ['GET'])]
    public function propias(UsuarioRepository $usuarioRepository,PartidaRepository $partidaRepository): Response{
        $user = $usuarioRepository->find($this->getUser());
        $partidas = $user->getPartidas(); $array = [];
        for ($i=0; $i < count($partidas) ; $i++) { 
            $array[$i] = $partidas[$i];
        }
        //$p = $personajeRepository->findAll();
        return $this->render('partida/propias.html.twig', [
            'partidas' => $array,
            
        ]);
    }
    
    #[Route('/new', name: 'partida_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $partida = new Partida();
        $form = $this->createForm(PartidaType::class, $partida);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($partida);
            $entityManager->flush();

            return $this->redirectToRoute('partida_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('partida/new.html.twig', [
            'partida' => $partida,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'partida_show', methods: ['GET'])]
    public function show(Partida $partida): Response
    {
        return $this->render('partida/show.html.twig', [
            'partida' => $partida,
        ]);
    }

    #[Route('/{id}/edit', name: 'partida_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Partida $partida): Response
    {
        $form = $this->createForm(PartidaType::class, $partida);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('partida_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('partida/edit.html.twig', [
            'partida' => $partida,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/anadir', name: 'partida_anadir', methods: ['GET', 'POST'])]
    public function anadir(UsuarioRepository $usuarioRepository, Partida $partida, PartidaRepository $partidaRepository,$id): Response
    {

        $user = $usuarioRepository->find($this->getUser());

        $party = $partidaRepository->find($id);

        

        dump($party);
        $array = $user->getPersonajes();

        return $this->render('partida/anadir.html.twig', [
            'partidas' => $array, 'partys' => $party,
           
        ]);
    }

    #[Route('/person', name: 'partida_person', methods: ['GET', 'POST'])]
    public function person(Request $request,EntityManagerInterface $em,PersonajeRepository $personajeRepository, 
    UsuarioRepository $usuarioRepository, PartidaRepository $partidaRepository): Response
    {        
        $id = $request->request->get('id');


        $partida = $partidaRepository->find($id);

        $nombre = $request->request->get('personaje');



        $per = $personajeRepository->findOneBy(['Nombre' => $nombre]);
        
        $partida->addPersonaje($per);

        $em->persist($partida);

        $em->flush();


        return $this->renderForm('partida/index.html.twig', [
            'partidas' => $partidaRepository->findAll()
           
        ]);
    }

    #[Route('/{id}', name: 'partida_delete', methods: ['POST'])]
    public function delete(Request $request, Partida $partida): Response
    {
        if ($this->isCsrfTokenValid('delete'.$partida->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($partida);
            $entityManager->flush();
        }

        return $this->redirectToRoute('partida_index', [], Response::HTTP_SEE_OTHER);
    }
}

Dicedragons/templates/partida/_delete_form.html.twig
<form method="post" action="{{ path('partida_delete', {'id': partida.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ partida.id) }}">
    <button class="btn">Delete</button>
</form>

Dicedragons/templates/partida/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Dicedragons/templates/partida/anadir.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dice & Dragons{% endblock %}

{% block body %} 

    <div class="container container1270">
        <h1>Crear Nuevo Personaje</h1>
       
    </div>
<br><br><br>

  <section class="container container1270">
<div>
      

           
       
    <form method="post" action="{{ path('partida_person') }}">
        
        <label for="id_clase">Personajes</label> 
        <select id="id_clase" name="personaje">
        {% for partida in partidas %}
            <option value='{{partida.nombre}}'> {{partida.nombre}} </option>
        {% endfor %}

        
       

            
        </select><br><br>
       <input type="number" name="id" value="{{partys.id}}" min="{{partys.id}}" max ="{{partys.id}}"><br><br>
        <input type="submit" name="Enviar" class="bot">
    </form>
               

        
    </div>

</section>

{% endblock %}

Dicedragons/templates/partida/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dice & Dragons{% endblock %}

{% block body %}
    <h1>Edit Partida</h1>

    {{ include('partida/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('partida_index') }}">back to list</a>

    {{ include('partida/_delete_form.html.twig') }}
{% endblock %}

Dicedragons/templates/partida/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Partida index{% endblock %}

{% block body %}
    <h1>Partida index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Proxima_sesion</th>
                <th>DM</th>
                <th>Personajes</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for partida in partidas %}
            <tr>
                <td>{{ partida.id }}</td>
                <td>{{ partida.ProximaSesion ? partida.ProximaSesion|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ partida.usuario.id }}</td> <td>
                {% for personajes in partida.personajes %}
                   {{ personajes.nombre }} ({{ personajes.id }}). 
                {% endfor %}</td>
                <td>
                    <a href="{{ path('partida_show', {'id': partida.id}) }}">show</a>
                    <a href="{{ path('partida_anadir', {'id': partida.id}) }}">Añadir personaje</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('partida_new') }}">Create new</a>
{% endblock %}

Dicedragons/templates/partida/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dice & Dragons{% endblock %}

{% block body %}
    <h1>Crear nueva Partida</h1>

    {{ include('partida/_form.html.twig') }}

    <a href="{{ path('partida_index') }}">back to list</a>
{% endblock %}

Dicedragons/templates/partida/propias.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dice & Dragons{% endblock %}

{% block body %}
    <h1>Partida index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Proxima_sesion</th>
                <th>DM</th>
                <th>Personajes</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for partida in partidas %}
            <tr>
                <td>{{ partida.id }}</td>
                <td>{{ partida.ProximaSesion ? partida.ProximaSesion|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ partida.usuario.id }}</td> <td>
                {% for personajes in partida.personajes %}
                   {{ personajes.nombre }} ({{ personajes.id }}). 
                {% endfor %}</td>
                <td>
                   
                    <a href="{{ path('partida_anadir', {'id': partida.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('partida_new') }}">Create new</a>
{% endblock %}

Dicedragons/templates/partida/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dice & Dragons{% endblock %}

{% block body %}
    <h1>Partida</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ partida.id }}</td>
            </tr>
            <tr>
                <th>Proxima_sesion</th>
                <td>{{ partida.ProximaSesion ? partida.ProximaSesion|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('partida_index') }}">back to list</a>

    <a href="{{ path('partida_edit', {'id': partida.id}) }}">edit</a>

    {{ include('partida/_delete_form.html.twig') }}
{% endblock %}